#!/bin/sh
#
# /usr/local/sbin/capslock
#
# This script is invoked by
# /etc/udev/rules.d/85-capslock-disable.rules

set -e

# Bring in my getXauthority function
. /usr/local/share/acpi-support/power-funcs

# On each active X display, disable capslock
for x in /tmp/.X11-unix/*; do
    export DISPLAY=:`echo $x | sed s#/tmp/.X11-unix/X##`
    getXauthority $DISPLAY 

    # Doing a direct xmodmap here either doesn't work at all, or
    # occasionally we'll get caps lock acting as control but the
    # external keyboard's capslock LED will still toggle.  Clearly
    # something is leaping in and undoing the good work we have done.
    #
    # Instead, fork a process using screen, wait a bit (yes, that
    # delay is needed) and then fix things.  This oughta be easier :(
    screen -d -m sh -c 'sleep 0.1 && xmodmap -e "remove Lock = Caps_Lock" -e "add Control = Caps_Lock"'
done
